import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export function formatCurrency(value: number) {
  if (isNaN(value) || value === undefined || value === null) {
    return "₱0.00";
  }
  return new Intl.NumberFormat("en-PH", {
    style: "currency",
    currency: "PHP",
  }).format(value);
}

/**
 * BuildbotAI Currency Utility
 * Converts USD SRP to PHP with a safety buffer of 1:60
 */
export const USD_TO_PHP_RATE = 60;

export const formatToPHP = (usdAmount: number): string => {
  // 1. Convert to PHP using the safety rate
  const phpAmount = usdAmount * USD_TO_PHP_RATE;

  // 2. Format as Philippine Peso currency
  return new Intl.NumberFormat('en-PH', {
    style: 'currency',
    currency: 'PHP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(phpAmount);
};

/**
 * Converts a standard Firebase Storage URL to the optimized 600x600 version
 * generated by the Resize Images extension.
 */
export function getOptimizedStorageUrl(url: string | undefined): string {
  if (!url) return "";
  
  // Only process actual Firebase Storage URLs
  if (!url.includes("firebasestorage.googleapis.com")) return url;
  
  // If it's already optimized or a data URL, skip
  if (url.includes("_600x600") || url.startsWith("data:")) return url;

  try {
    // 1. Extract the base URL (remove tokens/query params)
    const baseUrl = url.split("?")[0];
    
    // 2. Find the extension and insert the suffix. 
    // Since the extension converts everything to WebP, we force that extension here.
    const lastDotIndex = baseUrl.lastIndexOf(".");
    if (lastDotIndex === -1) return url;

    const prefix = baseUrl.substring(0, lastDotIndex);
    
    // We append the suffix and force .webp
    const optimizedUrl = `${prefix}_600x600.webp`;
    
    // 3. Return the URL with alt=media for public access
    // This works because the extension makes the resized images public
    // and our storage rules allow public read.
    return `${optimizedUrl}?alt=media`;
  } catch (error) {
    console.warn("[Utils] Failed to optimize storage URL:", error);
    return url;
  }
}
