export const componentCategories = [
  "CPU", "GPU", "Motherboard", "RAM", "Storage", "PSU", "Case", "Cooler",
  "Monitor", "Keyboard", "Mouse", "Headset",
];

export const CATEGORY_SPECS: Record<string, { key: string; placeholder: string; options?: string[] }[]> = {
  CPU: [
    { key: "Architecture", placeholder: "e.g., Zen 4" },
    { key: "Cores", placeholder: "e.g., 8" },
    { key: "Threads", placeholder: "e.g., 16" },
    { key: "Base Clock (GHz)", placeholder: "e.g., 4.5 GHz" },
    { key: "Boost Clock (GHz)", placeholder: "e.g., 5.4 GHz" },
    { key: "Socket", placeholder: "e.g., AM5" },
    { key: "TDP / Peak Power", placeholder: "e.g., 105 W" },
    { key: "L3 Cache", placeholder: "e.g., 32 MB" },
    { key: "Memory Support", placeholder: "e.g., DDR5" },
    { key: "Integrated Graphics", placeholder: "e.g., Yes / No" },
  ],
  GPU: [
    { key: "Chipset", placeholder: "e.g., RTX 4070" },
    { key: "VRAM Capacity", placeholder: "e.g., 12 GB" },
    { key: "Memory Type", placeholder: "e.g., GDDR6X" },
    { key: "TGP / Power Draw (W)", placeholder: "e.g., 200 W" },
    { key: "Length (Depth) (mm)", placeholder: "e.g., 336 mm" },
    { key: "Slot Thickness", placeholder: "e.g., 3" },
    { key: "Interface", placeholder: "e.g., PCIe 4.0 x16" },
    { key: "CUDA Cores", placeholder: "e.g., 5888 (NVIDIA) / Stream Processors" },
  ],
  Motherboard: [
    { key: "Chipset", placeholder: "e.g., B650" },
    { key: "Socket", placeholder: "e.g., AM5" },
    { key: "Form Factor", placeholder: "e.g., ATX" },
    { key: "RAM Type", placeholder: "e.g., DDR5" },
    { key: "SATA Slots", placeholder: "e.g., 6" },
    { key: "NVMe Slots", placeholder: "e.g., 3" },
    { key: "Memory Slots", placeholder: "e.g., 4" },
    { key: "Memory Type", placeholder: "e.g., DDR5" },
  ],
  RAM: [
    { key: "Generation", placeholder: "e.g., DDR5" },
    { key: "Capacity", placeholder: "e.g., 32 GB, 16 GB, 8 GB" },
    { key: "Speed", placeholder: "e.g., 6000 MT/s" },
    { key: "CAS Latency", placeholder: "e.g., CL30" },
    { key: "Stick Count", placeholder: "e.g., 1 or 2" },
  ],
  Storage: [
    { key: "Interface", placeholder: "e.g., NVMe M.2 / SATA" },
    { key: "Capacity", placeholder: "e.g., 1 TB" },
    { key: "Read Speed", placeholder: "e.g., 7000 MB/s" },
    { key: "Write Speed", placeholder: "e.g., 6500 MB/s" },
    { key: "TBW Rating", placeholder: "e.g., 600 TBW" },
    { key: "Form Factor", placeholder: "e.g., M.2 2280" },
    { key: "Type", placeholder: "Select drive type", options: ["SATA", "NVME"] },
  ],
  PSU: [
    { key: "Wattage (W)", placeholder: "e.g., 850 W" },
    { key: "Efficiency Rating", placeholder: "e.g., 80+ Gold" },
    { key: "Modularity", placeholder: "e.g., Fully Modular" },
    { key: "12VHPWR Support", placeholder: "e.g., Native ATX 3.0 / ATX 3.1" },
    { key: "Form Factor", placeholder: "e.g., ATX / SFX" },
    { key: "Width (mm)", placeholder: "150" },
    { key: "Depth (mm)", placeholder: "140" },
    { key: "Height (mm)", placeholder: "86" },
  ],
  Case: [
    { key: "Width (mm)", placeholder: "e.g., 210" },
    { key: "Depth (mm)", placeholder: "e.g., 450" },
    { key: "Height (mm)", placeholder: "e.g., 480" },
    { key: "Mobo Support", placeholder: "Motherboard compatibility" },
    { key: "Radiator Support (mm)", placeholder: "Radiator size support" },
    { key: "Type", placeholder: "Case form factor type" },
    { key: "Case Type", placeholder: "Fish Tank / High Air Flow" },
    { key: "Back-Connect Cutout", placeholder: "Yes / No" },
    { key: "PSU Form Factor", placeholder: "e.g., ATX / SFX" },
  ],
  Cooler: [
    { key: "TDP Rating", placeholder: "e.g., 250 W" },
    { key: "Socket Support", placeholder: "e.g., AM4, AM5, LGA1700" },
    { key: "Height", placeholder: "e.g., 165 mm" },
    { key: "Radiator Size", placeholder: "e.g., 360 mm" },
    { key: "Type", placeholder: "e.g., Air / AIO Liquid" },
  ],
  Monitor: [
    { key: "Screen Size", placeholder: "e.g., 27 inch" },
    { key: "Resolution", placeholder: "e.g., 2560 x 1440" },
    { key: "Refresh Rate", placeholder: "e.g., 144 Hz" },
    { key: "Panel Type", placeholder: "e.g., IPS / VA / OLED" },
    { key: "Response Time", placeholder: "e.g., 1ms GtG" },
  ],
  Keyboard: [
    { key: "Type", placeholder: "e.g., Mechanical / Membrane" },
    { key: "Switches", placeholder: "e.g., Cherry MX Red" },
    { key: "Layout", placeholder: "e.g., Full Size / TKL / 60%" },
    { key: "Backlighting", placeholder: "e.g., RGB / Single Color" },
  ],
  Mouse: [
    { key: "Sensor", placeholder: "e.g., Hero 25K" },
    { key: "DPI", placeholder: "e.g., 25600" },
    { key: "Connectivity", placeholder: "e.g., Wired / Wireless" },
    { key: "Weight", placeholder: "e.g., 63g" },
  ],
  Headset: [
    { key: "Type", placeholder: "e.g., Over-Ear / In-Ear" },
    { key: "Connectivity", placeholder: "e.g., Wired / Wireless / Bluetooth" },
    { key: "Driver Size", placeholder: "e.g., 50mm" },
    { key: "Microphone", placeholder: "e.g., Detachable / Built-in" },
  ],
};
