// This file is automatically generated by Firebase Studio
// Do not edit this file manually

export const firebaseConfig = {
  apiKey: "AIzaSyB32Ek1ehBBqFBSQEErw03FS9QVUK9fVYk",
  authDomain: "studio-3150054754-c7d0b.firebaseapp.com",
  projectId: "studio-3150054754-c7d0b",
  storageBucket: "studio-3150054754-c7d0b.appspot.com",
  messagingSenderId: "781722135778",
  appId: "1:781722135778:web:01a5a7d6148bf08b6e82bb",
};
